server:
  port: 8060
  error:
    include-stacktrace: never
spring:
  application:
    name: picpay-challenge
  datasource:
    url: jdbc:mysql://localhost:3306/picpay-challenge?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ROOT_USER:root}
    password: ${ROOT_PASSWORD:example}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: debug
